# 推荐目录结构:
#  root
#  ├── assets (存放资源)
#  ├── md     (存放md文件)
#  ├── md.bak (存放生成的备份md文件)
#  └── tool   (存放本工具)

# 原markdown文件目录/文件名
originMarkdownRootPath: /Users/heyingliang/myTemp/root/md2/Learning/Celery/网站__Celery中文文档/网站__Celery中文文档.md

# 迁移后的资源目录名
newResourceRootDirPath: /Users/heyingliang/myTemp/blog/source/images
# 迁移后的md目录/文件名
newMarkdownRootPath: /Users/heyingliang/myTemp/blog/source/_posts/Celery/网站__Celery中文文档/网站__Celery中文文档.md

# 本地md文件的后缀
markdownFileSuffix: .md
# 本地图片使用绝对路径
localPictureUseAbsPath: true

# 使用的处理策略,目前支持的功能:(注意顺序)
# CollectLocalPicture         : 下载网络资源,并将其放到assets目录中
# CollectNetWorkPicture       : 将所有本地资源合并到assets目录中
# TODO(暂不支持)
# UploadLocalPictureToNetWork : 将本地图片上传至网络中
# ExportMarkdown              : 将markdown文件连同所用资源导出
strategies:
  - CollectNetWorkPicture
  - CollectLocalPicture