# 推荐目录结构:
#  root
#  ├── assets (存放资源)
#  ├── md     (存放md文件)
#  └── tool   (存放本工具)

# 上述目录结构的资源目录名
resourceDirPath: D:\tmp\root\assets
# 上述目录结构的markdown文件目录名
markdownDirPath: C:\Users\12516\Dropbox\root\md
# 产生新的md目录名
newMarkdownDirPath: D:\tmp\root\md2

# 本地md文件的后缀
markdownFileSuffix: .md

# 本地图片使用绝对路径
localPictureUseAbsPath: false

# 使用的处理策略,目前支持的功能:(注意顺序)
# CollectLocalPicture         : 下载网络资源,并将其放到assets目录中
# CollectNetWorkPicture       : 将所有本地资源合并到assets目录中
# TODO(暂不支持)
# UploadLocalPictureToNetWork : 将本地图片上传至网络中
# ExportMarkdown              : 将markdown文件连同所用资源导出
strategies:
  - CollectNetWorkPicture
  - CollectLocalPicture